# Generated by Django 5.0.6 on 2026-02-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0004_add_timestamps_and_decimal_price'),
        ('base_feature_app', '0004_blog_created_at_blog_updated_at_product_created_at_and_more'),
    ]

    operations = [
    ]
