# Generated by Django 5.0.6 on 2024-06-08 02:14

import base_feature_app.models.product
import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20, validators=[base_feature_app.models.product.validate_ref])),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Bracelets', 'Bracelets'), ('Necklaces', 'Necklaces'), ('Earrings', 'Earrings'), ('Rings', 'Rings'), ('Watches', 'Watches'), ('Brooches', 'Brooches'), ('Anklets', 'Anklets'), ('Hair Jewelry', 'Hair Jewelry'), ('Cufflinks', 'Cufflinks'), ('Pendants', 'Pendants'), ('Charms', 'Charms'), ('Body Jewelry', 'Body Jewelry')], max_length=20)),
                ('gallery', django_attachments.fields.GalleryField(on_delete=django.db.models.deletion.CASCADE, related_name='products_with_attachment', to='django_attachments.library')),
            ],
        ),
    ]
